### ISSUE TITLE
[Feature Request]: Make this into an Extensions 

### ISSUE THREAD

**Issue by leohu1** [catppuccin/stable-diffusion-webui#1]
Make this into an Extensions for stable-diffusion-webui.

**Comment by Gerschel** [comment]
These project files will need to be updated to work with the extension, but there currently is an extension that I had put together before this project existed. I wish I had more theme contributors to be honest, even if not directly, but a list to compatible themes. The issue I run in to, most that put together a theme or color choices, don't keep them updated, and it leaves myself or Nacurutu to fix them. Just yesterday, we decided to not support those themes for the time, so we can focus on some updates.  
I popped in here to see if they were handling updates to their themes. I don't have a copy of them, because I was told specifically that I can't include them. But now they just added a license that allows copying and modifying as long as they hold copyright of their work, but I would need to modify them to catch them up with the webui's changes. On that same note, if I want to focus on adding content to work with the features I created, such as special effects, favicons, logos, background image placement, I don't have the time to modify every theme template.    
However, I do have an import feature, where you can import and test if these themes do work, it will open a file explorer, that you can paste in the url of the raw version of the file, and it will save it as a file on your computer.  

@catppuccin 
The idea behind my theme engine is for creators to have an easier way to bundle special effects, background images, favicon, and css, to create a full theme. Think of it like, I want a mint chocolate chunk theme, so you can set your colors in the css, but also specify the favicon and it will be forced (just added support for that last night), give a user the option to change the chocolate chunks from one to another (background image injection is present, it's dynamic, need to settle on a way for css sheet to declare rules, I need feedback so I can extend it properly), maybe choose something like the matrixeffect, but can declare they want emojis, or some svg image and change the rate of fall ( and make other special effects that allow modification, like coloring rain if someone wanted to build a toxic environment or other worldly fantasy), etc.  

https://github.com/Gerschel/sd-web-ui-quickcss

**Comment by Kettukaa** [comment]
Thanks for bringing this back up! I haven't had a chance to add to the theme over the past few days, but will soon. I will look more at your repo when I do. It probably would be a really good way to keep themes up to date and CSS simpler.

**Comment by Kettukaa** [comment]
If you'd like @Gerschel, you can join our discord server and help us migrate the theme over https://discord.gg/catppuccin we have a subchannel in Projects called "Stable Diffusion WebUI + Gradio"

**Comment by Kettukaa** [comment]
@Gerschel It seemed easier to just make our own extension instead of migrating the whole theme to your system. 

@leohu1 It is an extension now :)
