### ISSUE TITLE
Not an extension, this applies 1 direction and is not undoable (Cannot enable/Disable)

### ISSUE THREAD

**Issue by Reinbowsaur** [catppuccin/stable-diffusion-webui#5]
This "extension" applies to the users Webui permanantly and is not easily removable, quite annoying, and hard to locate files for customization.

**Comment by Reinbowsaur** [comment]
Realized my problem, since this extension is using a default name I kept glazing over it unable to find it and hence modify/disable it. Thanks for the extension, I suggest giving it a unique name!

**Comment by Kettukaa** [comment]
> Realized my problem, since this extension is using a default name I kept glazing over it unable to find it and hence modify/disable it. Thanks for the extension, I suggest giving it a unique name!

Yeah, unfortunately due to Catppuccin naming conventions, the repo name is just "stable-diffusion-webui",and WebUI gets extension names from repo names. I have proposed a solution to this [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7539#issue-1571127595). If you want a better chance of this being solved, then you should upvote that issue :)

**Comment by Kettukaa** [comment]
Though, given that this can cause issues and be confusing, I'm going to add some clarification in the readme.
